package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"

	"github.com/Shuri-Honda-1101/ent-bug-fragment/ent"
	"github.com/Shuri-Honda-1101/ent-bug-fragment/gql"
)

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input ent.CreateTaskInput) (*ent.Task, error) {
	task, err := r.client.Task.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return task, nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id *int, input ent.UpdateTaskInput) (*ent.Task, error) {
	task, err := r.client.Task.UpdateOneID(*id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return task, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, input ent.CreateProjectInput) (*ent.Project, error) {
	project, err := r.client.Project.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return project, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id *int, input ent.UpdateProjectInput) (*ent.Project, error) {
	project, err := r.client.Project.UpdateOneID(*id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return project, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input ent.CreateUserInput) (*ent.User, error) {
	user, err := r.client.User.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id *int, input ent.UpdateUserInput) (*ent.User, error) {
	user, err := r.client.User.UpdateOneID(*id).SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return user, nil
}

// Mutation returns gql.MutationResolver implementation.
func (r *Resolver) Mutation() gql.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
